# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.3
curseforge_minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=0.1.6
maven_group=me.drex
archives_base_name=orderedplayerlist
# Dependencies
fabric_version=0.161.0+26.3
permission_api_version=0.7.0
placeholder_api_version=3.2.0+26.3
