# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.2
curseforge_minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.1.6
maven_group=me.drex
archives_base_name=orderedplayerlist
# Dependencies
fabric_version=0.152.1+26.2
permission_api_version=0.7.0
placeholder_api_version=3.1.0-beta.1+26.2
