# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.1
curseforge_minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
mod_version=0.1.6
maven_group=me.drex
archives_base_name=orderedplayerlist
# Dependencies
fabric_version=0.144.1+26.1
permission_api_version=0.7.0
placeholder_api_version=3.0.0-beta.2+26.1
